namespace: 
  name: prod

labels:
  tag: apline

deployment:
  replicas: 2
  cpuLimit: 70m
  memoryLimit: 128Mi

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80	

configmap:
  data: "version: 1.17.0"
